project_id = "fsayiuhncisevhipbrak"

[functions.import-popular-exercises]
verify_jwt = false

[functions.import-exercises-exercisedb]
verify_jwt = false

[functions.import-exercises-community]
verify_jwt = false
