import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { Dumbbell, Brain, Zap, Plus, History } from 'lucide-react';
import { ProgramBuilderForm, ProgramPreview, useAIPrograms } from '@/features/ai-coach';
import DebugPanel from '@/components/debug/DebugPanel';


export default function BroAICoach() {
  const [activeTab, setActiveTab] = useState('build');
  const [selectedProgramId, setSelectedProgramId] = useState<string | null>(null);
  const { data: programs = [], isLoading } = useAIPrograms();

  const selectedProgram = programs.find(p => p.id === selectedProgramId);

  const handleProgramGenerated = (programId: string) => {
    setSelectedProgramId(programId);
    setActiveTab('preview');
  };

  return (
    <>

      <div className="min-h-screen bg-gradient-subtle">
        <div className="container mx-auto px-4 py-8">
          {/* Hero Section */}
          <div className="text-center mb-8">
            <div className="flex items-center justify-center gap-3 mb-4">
              <div className="relative">
                <Brain className="h-12 w-12 text-primary" />
                <Zap className="h-6 w-6 text-amber-500 absolute -top-1 -right-1" />
              </div>
              <h1 className="text-4xl font-bold bg-gradient-primary bg-clip-text text-transparent">
                Bro AI Coach
              </h1>
            </div>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Get personalized workout programs generated by AI. 
              Built by bros, for bros who want to maximize their gains.
            </p>
          </div>

          <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
            <TabsList className="grid w-full grid-cols-3 max-w-md mx-auto">
              <TabsTrigger value="build" className="flex items-center gap-2">
                <Plus className="h-4 w-4" />
                Build
              </TabsTrigger>
              <TabsTrigger value="preview" disabled={!selectedProgram}>
                <Dumbbell className="h-4 w-4" />
                Preview
              </TabsTrigger>
              <TabsTrigger value="history" className="flex items-center gap-2">
                <History className="h-4 w-4" />
                My Programs
              </TabsTrigger>
            </TabsList>

            <TabsContent value="build" className="mt-8">
              <ProgramBuilderForm onProgramGenerated={handleProgramGenerated} />
            </TabsContent>

            <TabsContent value="preview" className="mt-8">
              {selectedProgram ? (
                <ProgramPreview 
                  program={selectedProgram}
                  onStartProgram={() => {
                    // TODO: Implement program starting logic
                    console.log('Starting program:', selectedProgram.id);
                  }}
                />
              ) : (
                <Card className="max-w-2xl mx-auto text-center">
                  <CardContent className="py-12">
                    <Dumbbell className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
                    <h3 className="text-lg font-medium mb-2">No Program Selected</h3>
                    <p className="text-muted-foreground mb-4">
                      Generate a new program or select one from your history to preview it.
                    </p>
                    <Button onClick={() => setActiveTab('build')}>
                      <Plus className="h-4 w-4 mr-2" />
                      Build New Program
                    </Button>
                  </CardContent>
                </Card>
              )}
            </TabsContent>

            <TabsContent value="history" className="mt-8">
              <Card className="max-w-4xl mx-auto">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <History className="h-5 w-5" />
                    My AI Programs
                  </CardTitle>
                  <p className="text-muted-foreground">
                    All the programs Bro AI has created for you
                  </p>
                </CardHeader>
                <CardContent>
                  {isLoading ? (
                    <div className="text-center py-8">
                      <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto mb-4" />
                      <p className="text-muted-foreground">Loading your programs...</p>
                    </div>
                  ) : programs.length === 0 ? (
                    <div className="text-center py-8">
                      <Dumbbell className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
                      <h3 className="text-lg font-medium mb-2">No Programs Yet</h3>
                      <p className="text-muted-foreground mb-4">
                        You haven't generated any AI programs yet. Create your first one!
                      </p>
                      <Button onClick={() => setActiveTab('build')}>
                        <Plus className="h-4 w-4 mr-2" />
                        Generate First Program
                      </Button>
                    </div>
                  ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {programs.map((program) => (
                        <Card 
                          key={program.id} 
                          className={`cursor-pointer transition-all hover:shadow-md ${
                            selectedProgramId === program.id ? 'ring-2 ring-primary' : ''
                          }`}
                          onClick={() => {
                            setSelectedProgramId(program.id);
                            setActiveTab('preview');
                          }}
                        >
                          <CardHeader className="pb-3">
                            <div className="flex items-start justify-between">
                              <CardTitle className="text-lg">{program.name}</CardTitle>
                              <Badge 
                                variant={program.is_active ? 'default' : 'outline'}
                                className="text-xs"
                              >
                                {program.is_active ? 'Active' : 'Inactive'}
                              </Badge>
                            </div>
                            <div className="flex items-center gap-2 text-sm text-muted-foreground">
                              <span>AI Generated</span>
                              <span>•</span>
                              <span>{program.description ? program.description.slice(0, 50) + '...' : 'Training Program'}</span>
                            </div>
                          </CardHeader>
                          <CardContent>
                            <div className="flex items-center justify-between">
                              <div className="text-sm text-muted-foreground">
                                Created {new Date(program.created_at).toLocaleDateString()}
                              </div>
                              <Button variant="outline" size="sm">
                                View Program
                              </Button>
                            </div>
                          </CardContent>
                        </Card>
                      ))}
                    </div>
                  )}
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        </div>
        
        <DebugPanel forceOpen={true} />
      </div>
    </>
  );
}