// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsayiuhncisevhipbrak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzYXlpdWhuY2lzZXZoaXBicmFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2OTc1ODAsImV4cCI6MjA3MDI3MzU4MH0.m6Q6-kyLfctBMaoUvuOOaAH2T6GP8T8MRy_ctSzmszw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});