export type TipsEntry = { title: string; tips: string[] };
export const TIPS_BY_SLUG: Record<string, TipsEntry> = {
  // ---------- HEALTH ----------
  "fitness-exercise": { title: "Health · Fitness & Exercise", tips: [
    "Plan 3–5 sessions/week; put them on your calendar.",
    "Progress loads or reps gradually (≈5–10%).",
    "Prioritize compound lifts before accessories.",
    "Warm up the specific pattern, not just general cardio.",
    "Track sets, reps, and effort (RPE) to guide progression.",
    "Sleep and protein drive recovery—protect both.",
    "Deload for a week every 6–8 demanding weeks.",
    "Use full, controlled range of motion; no ego lifting.",
    "Stop 1–3 reps short of failure for most working sets.",
    "Consistency beats intensity spikes—adjust volume if busy.",
  ]},
  "nutrition-hydration": { title: "Health · Nutrition & Hydration", tips: [
    "Build plates: protein + plants + fiber + healthy fat.",
    "Hit a protein floor (~0.8–1.2 g/kg/day).",
    "Favor minimally processed foods most of the time.",
    "Hydrate regularly; start the day with water.",
    "Judge by weekly averages, not daily perfection.",
    "Keep 3–5 go-to meals preplanned.",
    "Keep fruits/veg visible to bias choices.",
    "Limit liquid calories and sneaky sauces.",
    "Eat slowly; stop at comfortably satisfied.",
    "Change one habit per week, not ten.",
  ]},
  "sleep-quality": { title: "Health · Sleep Quality", tips: [
    "Keep a consistent sleep/wake schedule (weekends too).",
    "Wind down 30–60 min (lights low, no doom scrolling).",
    "Cool, dark, quiet bedroom; comfy bedding.",
    "Caffeine cutoff 6–8 hours before bed.",
    "Get morning light; move your body daily.",
    "If awake >20 min, get up and do something relaxing.",
    "Power naps <30 min, early afternoon.",
    "Avoid heavy meals and alcohol late.",
    "Manage stress before bed (breathing, journaling).",
    "See a clinician if issues persist (e.g., snoring, apneas).",
  ]},
  "medical-checkups": { title: "Health · Medical Checkups", tips: [
    "Book an annual physical and keep it recurring.",
    "Track vaccinations/boosters in one place.",
    "Follow age-appropriate screenings.",
    "Maintain an up-to-date meds/supps list.",
    "Know family history & risk factors.",
    "Prep questions and priorities before visits.",
    "Bring recent home measurements (BP, glucose).",
    "Confirm next steps before leaving the clinic.",
    "Save results; set follow-up reminders.",
    "Seek a second opinion when uncertain.",
  ]},
  "energy-levels": { title: "Health · Energy Levels", tips: [
    "Anchor sleep/meals; avoid big timing swings.",
    "Hydrate early; 5-minute movement breaks beat slumps.",
    "Pair carbs with protein/fat to smooth energy.",
    "Do deep work at your personal energy peak.",
    "Reduce multitasking; batch similar tasks.",
    "Sunlight + short walk > another coffee.",
    "Limit alcohol—sleep fragmentation crushes energy.",
    "Track stress and add micro-recovery slots.",
    "Use caffeine strategically, not habitually.",
    "Review weekly patterns; tweak one lever.",
  ]},

  // ---------- MIND & EMOTIONS ----------
  "stress-management": { title: "Mind & Emotions · Stress Management", tips: [
    "Name stressors; separate controllable from not.",
    "Use micro-breaks (breathing, walk, box breathing).",
    "Schedule recovery like meetings.",
    "Keep basics: sleep, movement, nutrition.",
    "Limit constant news/social input.",
    "Use 'worry time' to contain rumination.",
    "Delegate or delete low-value tasks.",
    "Talk it out with a trusted person.",
    "Practice gratitude journaling (2–3 items).",
    "Seek therapy/coaching when stuck.",
  ]},
  "mindfulness-meditation": { title: "Mind & Emotions · Mindfulness & Meditation", tips: [
    "Start with 3–5 minutes daily; consistency first.",
    "Anchor practice to an existing habit.",
    "Focus on breath or a simple anchor.",
    "Gently return when distracted (that IS the rep).",
    "Use body scans to tune awareness.",
    "Bring mini-pauses into the day.",
    "Don't chase 'blank mind'; notice & return.",
    "Use guided sessions if helpful.",
    "Reflect: what changed after practice?",
    "Track streaks to maintain momentum.",
  ]},
  "self-awareness": { title: "Mind & Emotions · Self-Awareness", tips: [
    "Daily 2-minute check-in: mood, energy, focus.",
    "Name emotions precisely; expand your vocabulary.",
    "Note triggers/patterns; design buffers.",
    "Ask for feedback from trusted peers.",
    "Identify values; align calendar with them.",
    "Track habits and outcomes to see cause→effect.",
    "Journal short prompts, not essays.",
    "Use 'if-then' plans for hot spots.",
    "Celebrate tiny wins to reinforce identity.",
    "Review weekly and adjust one thing.",
  ]},
  "emotional-regulation": { title: "Mind & Emotions · Emotional Regulation", tips: [
    "HALT scan (Hungry, Angry, Lonely, Tired) before reacting.",
    "Extend exhale; slow physiology first.",
    "Use grounding (5-4-3-2-1 senses).",
    "Label emotions; validation reduces intensity.",
    "Take time-outs for hot topics.",
    "Replace 'always/never' with specifics.",
    "Practice self-compassion statements.",
    "Plan repairs quickly after ruptures.",
    "Build buffers for predictable stressors.",
    "Get skilled support when needed.",
  ]},
  "therapy-mental-health": { title: "Mind & Emotions · Therapy & Mental Health", tips: [
    "Treat help-seeking as a performance tool.",
    "Pick goals for therapy; revisit monthly.",
    "Be honest; therapy is a 'truth zone'.",
    "Practice skills between sessions.",
    "Track symptoms weekly for trends.",
    "Combine with lifestyle pillars.",
    "Clarify meds questions with your prescriber.",
    "Use crisis resources when needed.",
    "Involve supportive people if helpful.",
    "Review progress and plan maintenance.",
  ]},

  // ---------- RELATIONSHIPS ----------
  "family-relationships": { title: "Relationships · Family", tips: [
    "Hold regular family check-ins (wins, needs, plans).",
    "Model emotion coaching; validate feelings.",
    "Create clear routines/roles; post them.",
    "Solve problems collaboratively, not punitively.",
    "Practice respectful conflict (no contempt).",
    "Protect family rituals (meals, walks).",
    "Align on boundaries and tech rules.",
    "Keep kids out of adult conflicts.",
    "Ask for help early (counselor/coach).",
    "Document what works; reuse in tough times.",
  ]},
  "romantic-life": { title: "Relationships · Romantic Life", tips: [
    "Make daily bids for connection; turn toward theirs.",
    "Keep positive:negative interactions ≈5:1.",
    "Schedule stress-reducing conversations.",
    "Replace criticism/defensiveness with curiosity.",
    "Maintain friendship inside the romance.",
    "Align expectations (money, chores, intimacy).",
    "Use time-outs when flooded; repair quickly.",
    "Share goals and rituals of connection.",
    "Express appreciation often and specifically.",
    "No relationship is perfect; keep growing.",
  ]},
  "friendships": { title: "Relationships · Friendships", tips: [
    "Show up consistently—rituals beat intentions.",
    "Assume people like you (liking gap is real).",
    "Practice active listening and follow-ups.",
    "Offer low-friction help/check-ins.",
    "Share small wins and struggles.",
    "Celebrate milestones; be reliable.",
    "Keep a high positivity ratio.",
    "Repair quickly after missteps.",
    "Audit your calendar for friend time.",
    "Create recurring hangouts.",
  ]},
  "community-social-skills": { title: "Relationships · Community & Social Skills", tips: [
    "Join small, regular groups; repetition builds bonds.",
    "Learn and use names quickly.",
    "Ask open questions; reflect back.",
    "Volunteer—shared goals accelerate trust.",
    "Host low-effort gatherings.",
    "Contribute before you ask.",
    "Follow up within 24–48 hours.",
    "Share resources/opportunities.",
    "Be consistent more than impressive.",
    "Rotate roles to grow skills.",
  ]},
  "networking-collaboration": { title: "Relationships · Networking & Collaboration", tips: [
    "Lead with value; share an insight or intro.",
    "Keep a simple CRM (notes + next step).",
    "Batch reach-outs weekly.",
    "Follow up on firsts in 5–7 days.",
    "Ask specific, easy favors.",
    "Co-create small wins first.",
    "Show, don't sell; demo outcomes.",
    "Close loops; say thanks.",
    "Be the connector among others.",
    "Stay helpful even when you don't need anything.",
  ]},

  // ---------- WEALTH ----------
  "income-career-growth": { title: "Wealth · Income & Career Growth", tips: [
    "Stack skills with market leverage.",
    "Keep a brag doc; quantify impact.",
    "Ask for feedback quarterly.",
    "Network internally and externally.",
    "Prepare for negotiation year-round.",
    "Ship visible wins regularly.",
    "Mentor and be mentored.",
    "Track offers and salary bands.",
    "Protect deep-work time.",
    "Align projects with business metrics.",
  ]},
  "saving-investing": { title: "Wealth · Saving & Investing", tips: [
    "Pay yourself first (automate).",
    "Build an emergency fund (3–6 months).",
    "Low-cost diversified funds as default.",
    "Avoid timing the market.",
    "Increase contributions annually.",
    "Keep separate long/short-term buckets.",
    "Minimize fees and taxes.",
    "Rebalance on a schedule.",
    "Don't chase hot tips.",
    "Stay the course; long horizon wins.",
  ]},
  "budgeting-debt": { title: "Wealth · Budgeting & Debt", tips: [
    "Track cash flow; give every dollar a job.",
    "Use the snowball/avalanche method for debts.",
    "Automate minimums + extra payment on target debt.",
    "Cut recurring waste first.",
    "Delay big wants for 72 hours.",
    "Build sinking funds for known expenses.",
    "Negotiate bills annually.",
    "Monitor credit and utilization.",
    "Avoid new debt during payoff.",
    "Celebrate milestones to keep momentum.",
  ]},
  "financial-education": { title: "Wealth · Financial Education", tips: [
    "Read one quality book per quarter.",
    "Follow evidence-based sources, not hype.",
    "Understand taxes enough to plan.",
    "Learn risk vs. return basics.",
    "Know your asset allocation.",
    "Understand interest compounding.",
    "Beware of conflicts/fees in advice.",
    "Practice with small amounts.",
    "Write an IPS (investment policy statement).",
    "Teach someone else to cement learning.",
  ]},
  "wealth-building": { title: "Wealth · Wealth Building", tips: [
    "Increase income and invest the spread.",
    "Own appreciating assets, not liabilities.",
    "Automate contributions.",
    "Avoid lifestyle creep; set caps.",
    "Diversify across asset classes.",
    "Own skills and IP where possible.",
    "Use leverage carefully.",
    "Protect downside (insurance, buffers).",
    "Review net worth quarterly.",
    "Think decades, not months.",
  ]},

  // ---------- PURPOSE & GROWTH ----------
  "career-purpose-or-calling": { title: "Purpose & Growth · Career / Purpose / Calling", tips: [
    "Write a personal mission draft.",
    "Map strengths → roles that need them.",
    "Prototype tiny experiments monthly.",
    "Shadow or interview people in roles.",
    "Keep a learning backlog.",
    "Ship public artifacts of your work.",
    "Seek environments that reward growth.",
    "Schedule reflection blocks.",
    "Document lessons learned.",
    "Iterate—purpose emerges by doing.",
  ]},
  "skill-development": { title: "Purpose & Growth · Skill Development", tips: [
    "Pick one skill per cycle; narrow the scope.",
    "Design deliberate practice with feedback.",
    "Track reps; measure improvement.",
    "Mix drills with real projects.",
    "Seek mentors/peers to review work.",
    "Space and interleave practice sessions.",
    "Publish progress logs.",
    "Automate or template repetitive steps.",
    "Teach others to solidify skill.",
    "Hold monthly 'demo day' for yourself.",
  ]},
  "hobbies-creativity": { title: "Purpose & Growth · Hobbies & Creativity", tips: [
    "Protect a weekly creativity block.",
    "Keep materials/tools visible and ready.",
    "Collect ideas; capture sparks immediately.",
    "Create before you consume.",
    "Finish small pieces; share them.",
    "Use constraints to unlock ideas.",
    "Collaborate for fresh inputs.",
    "Take intentional inspiration walks.",
    "Join a community or class.",
    "Celebrate making, not just outcomes.",
  ]},
  "continuous-learning": { title: "Purpose & Growth · Continuous Learning", tips: [
    "Run a learning roadmap per quarter.",
    "Alternate input (reading) with output (notes).",
    "Use spaced repetition for fundamentals.",
    "Summarize each source in your own words.",
    "Build projects from what you learn.",
    "Create a public notebook or blog.",
    "Discuss with peers to stress-test ideas.",
    "Revisit and prune notes monthly.",
    "Teach a session to cement concepts.",
    "Track ROI of learning time.",
  ]},
  "goal-setting": { title: "Purpose & Growth · Goal Setting", tips: [
    "Set one outcome per area max.",
    "Write clear leading indicators (habits).",
    "Break into weekly commitments.",
    "Pre-decide when/where you'll act.",
    "Do weekly reviews; adjust fast.",
    "Make progress visible (dash, checklist).",
    "Design rewards after key milestones.",
    "Remove friction and temptations.",
    "Pair up for accountability.",
    "Plan a 'next iteration' before finishing.",
  ]},

  // ---------- LIFESTYLE ----------
  "time-productivity": { title: "Lifestyle · Time & Productivity", tips: [
    "Time-box deep work; protect it.",
    "Plan the day the afternoon before.",
    "Batch shallow tasks.",
    "Use a single trusted task system.",
    "Limit WIP (work in progress).",
    "Default to 'no' then negotiate.",
    "Automate/reuse templates.",
    "Review weekly; clean the slate.",
    "Track where time actually goes.",
    "Finish tiny today; big tomorrow.",
  ]},
  "environment-organization": { title: "Lifestyle · Environment & Organization", tips: [
    "One-touch rule for items and files.",
    "Daily 10-minute reset habit.",
    "Label containers, not shelves.",
    "Create a landing zone for essentials.",
    "Keep work zone clutter-light.",
    "Digitize paperwork; set naming rules.",
    "Use checklists for repeating setups.",
    "Purge quarterly; donate responsibly.",
    "Design storage near point of use.",
    "Audit what's in your way—and remove it.",
  ]},
  "minimalism-sustainability": { title: "Lifestyle · Minimalism & Sustainability", tips: [
    "Define 'enough' for key categories.",
    "Buy once, buy well.",
    "Use the one-in, one-out rule.",
    "Repair before replacing.",
    "Choose multi-use items.",
    "Prefer experiences over stuff.",
    "Cut energy waste at home.",
    "Plan errands to reduce trips.",
    "Donate/sell unused items.",
    "Track savings from minimalism.",
  ]},
  "volunteering-giving-back": { title: "Lifestyle · Volunteering & Giving Back", tips: [
    "Pick a cause you'll stick with.",
    "Schedule recurring micro-volunteering.",
    "Leverage your professional skills.",
    "Join a community to stay engaged.",
    "Track hours/impact to stay motivated.",
    "Invite a friend; make it social.",
    "Mix direct help with donations.",
    "Learn from the org's feedback.",
    "Celebrate small wins publicly.",
    "Reflect on how it changes you.",
  ]},
  "legacy-projects": { title: "Lifestyle · Legacy Projects", tips: [
    "Define what 'legacy' means to you.",
    "Pick one project and scope it tiny.",
    "Create a time-boxed pilot.",
    "Document process so others can continue.",
    "Recruit a collaborator.",
    "Set public milestones.",
    "Archive artifacts well.",
    "Plan stewardship/maintenance.",
    "Measure impact stories, not only metrics.",
    "Leave instructions for hand-off.",
  ]},
};