-- Add English translations for equipment items
INSERT INTO equipment_translations (equipment_id, language_code, name, description) 
VALUES
-- Get equipment IDs and add translations
((SELECT id FROM equipment WHERE slug = 'olympic-barbell'), 'en', 'Olympic Barbell', 'Standard 45lb/20kg Olympic barbell'),
((SELECT id FROM equipment WHERE slug = 'ez-curl-bar'), 'en', 'EZ Curl Bar', 'Angled barbell for bicep and tricep exercises'),
((SELECT id FROM equipment WHERE slug = 'fixed-barbell'), 'en', 'Fixed Barbell', 'Pre-loaded fixed weight barbell'),
((SELECT id FROM equipment WHERE slug = 'dumbbell'), 'en', 'Dumbbell', 'Adjustable or fixed weight dumbbell'),
((SELECT id FROM equipment WHERE slug = 'kettlebell'), 'en', 'Kettlebell', 'Cast iron weight with handle for dynamic exercises'),
((SELECT id FROM equipment WHERE slug = 'weight-plate'), 'en', 'Weight Plate', 'Additional weight plates for barbells'),
((SELECT id FROM equipment WHERE slug = 'trap-bar'), 'en', 'Trap Bar', 'Hexagonal bar for deadlifts and shrugs'),
((SELECT id FROM equipment WHERE slug = 'sandbag'), 'en', 'Sandbag', 'Weighted sandbag for functional training'),
((SELECT id FROM equipment WHERE slug = 'cable-machine'), 'en', 'Cable Machine', 'Adjustable cable pulley system'),
((SELECT id FROM equipment WHERE slug = 'lat-pulldown-machine'), 'en', 'Lat Pulldown Machine', 'Machine for lat pulldown exercises'),
((SELECT id FROM equipment WHERE slug = 'flat-bench'), 'en', 'Flat Bench', 'Horizontal bench for pressing exercises'),
((SELECT id FROM equipment WHERE slug = 'incline-bench'), 'en', 'Incline Bench', 'Angled bench for incline pressing'),
((SELECT id FROM equipment WHERE slug = 'decline-bench'), 'en', 'Decline Bench', 'Declined bench for decline pressing'),
((SELECT id FROM equipment WHERE slug = 'pull-up-bar'), 'en', 'Pull-up Bar', 'Overhead bar for pull-ups and chin-ups'),
((SELECT id FROM equipment WHERE slug = 'dip-bars'), 'en', 'Dip Bars', 'Parallel bars for dip exercises'),
((SELECT id FROM equipment WHERE slug = 'smith-machine'), 'en', 'Smith Machine', 'Guided barbell machine with safety catches'),
((SELECT id FROM equipment WHERE slug = 'power-rack'), 'en', 'Power Rack', 'Squat rack with safety bars and pull-up bar'),
((SELECT id FROM equipment WHERE slug = 'leg-press-machine'), 'en', 'Leg Press Machine', 'Machine for leg press exercises'),
((SELECT id FROM equipment WHERE slug = 'leg-curl-machine'), 'en', 'Leg Curl Machine', 'Machine for hamstring curls'),
((SELECT id FROM equipment WHERE slug = 'leg-extension-machine'), 'en', 'Leg Extension Machine', 'Machine for quadriceps extensions'),
((SELECT id FROM equipment WHERE slug = 'seated-row-machine'), 'en', 'Seated Row Machine', 'Cable machine for seated rowing'),
((SELECT id FROM equipment WHERE slug = 'chest-press-machine'), 'en', 'Chest Press Machine', 'Machine for chest pressing movements'),
((SELECT id FROM equipment WHERE slug = 'shoulder-press-machine'), 'en', 'Shoulder Press Machine', 'Machine for overhead pressing'),
((SELECT id FROM equipment WHERE slug = 'preacher-bench'), 'en', 'Preacher Bench', 'Angled bench for preacher curls'),
((SELECT id FROM equipment WHERE slug = 'hyperextension-bench'), 'en', 'Hyperextension Bench', 'Bench for back extension exercises'),
((SELECT id FROM equipment WHERE slug = 'roman-chair'), 'en', 'Roman Chair', 'Equipment for back extensions and leg raises'),
((SELECT id FROM equipment WHERE slug = 'ab-crunch-machine'), 'en', 'Ab Crunch Machine', 'Machine for abdominal crunches'),
((SELECT id FROM equipment WHERE slug = 'calf-raise-machine'), 'en', 'Calf Raise Machine', 'Machine for calf raise exercises'),
((SELECT id FROM equipment WHERE slug = 'adductor-machine'), 'en', 'Adductor Machine', 'Machine for inner thigh exercises'),
((SELECT id FROM equipment WHERE slug = 'abductor-machine'), 'en', 'Abductor Machine', 'Machine for outer thigh exercises'),
((SELECT id FROM equipment WHERE slug = 'resistance-bands'), 'en', 'Resistance Bands', 'Elastic bands for resistance training'),
((SELECT id FROM equipment WHERE slug = 'suspension-trainer'), 'en', 'Suspension Trainer', 'Bodyweight training system with straps'),
((SELECT id FROM equipment WHERE slug = 'chains'), 'en', 'Chains', 'Heavy chains for variable resistance training'),
((SELECT id FROM equipment WHERE slug = 'free-weight-station'), 'en', 'Free Weight Station', 'Area with various free weights'),
((SELECT id FROM equipment WHERE slug = 'bodyweight'), 'en', 'Bodyweight', 'No equipment needed - bodyweight only'),
((SELECT id FROM equipment WHERE slug = 'medicine-ball'), 'en', 'Medicine Ball', 'Weighted ball for functional training'),
((SELECT id FROM equipment WHERE slug = 'battle-ropes'), 'en', 'Battle Ropes', 'Heavy ropes for cardio and strength training'),
((SELECT id FROM equipment WHERE slug = 'stability-ball'), 'en', 'Stability Ball', 'Large inflatable ball for core training'),
((SELECT id FROM equipment WHERE slug = 'bosu-ball'), 'en', 'BOSU Ball', 'Half stability ball for balance training'),
((SELECT id FROM equipment WHERE slug = 'foam-roller'), 'en', 'Foam Roller', 'Cylindrical tool for self-massage and recovery')
ON CONFLICT (equipment_id, language_code) DO UPDATE SET
name = EXCLUDED.name,
description = EXCLUDED.description;