-- Add Deadlift and Leg Curl exercises with correct enum types
INSERT INTO exercises (
  slug,
  display_name,
  custom_display_name,
  movement_pattern_id,
  load_type,
  exercise_skill_level,
  equipment_id,
  primary_muscle_id,
  body_part_id,
  complexity_score,
  is_bar_loaded,
  default_bar_weight,
  loading_hint,
  popularity_rank,
  is_public,
  owner_user_id,
  tags,
  secondary_muscle_group_ids
)
SELECT
  'barbell-deadlift',
  'Barbell Deadlift',
  'Barbell Deadlift',
  (SELECT id FROM movement_patterns WHERE slug = 'hinge'),
  'dual_load'::load_type_enum,
  'high'::exercise_skill_level_enum,
  (SELECT id FROM equipment WHERE slug = 'olympic-barbell'),
  (SELECT id FROM muscles WHERE slug = 'erector_spinae'),
  (SELECT id FROM body_parts WHERE slug = 'legs'),
  7,
  TRUE,
  20,
  'per_side',
  98,
  TRUE,
  NULL,
  ARRAY['compound','strength','hinge']::text[],
  ARRAY(SELECT id FROM muscle_groups WHERE slug IN ('glutes','hamstrings','traps','forearms') ORDER BY slug)::uuid[]
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug = 'barbell-deadlift');

INSERT INTO exercises (
  slug,
  display_name,
  custom_display_name,
  movement_pattern_id,
  load_type,
  exercise_skill_level,
  equipment_id,
  primary_muscle_id,
  body_part_id,
  complexity_score,
  is_bar_loaded,
  default_bar_weight,
  loading_hint,
  popularity_rank,
  is_public,
  owner_user_id,
  tags,
  secondary_muscle_group_ids
)
SELECT
  'machine-leg-curl',
  'Leg Curl (Machine)',
  'Leg Curl (Machine)',
  (SELECT id FROM movement_patterns WHERE slug = 'isolation'),
  'stack'::load_type_enum,
  'low'::exercise_skill_level_enum,
  (SELECT id FROM equipment WHERE slug = 'leg-curl-machine'),
  (SELECT id FROM muscles WHERE slug = 'biceps_femoris'),
  (SELECT id FROM body_parts WHERE slug = 'legs'),
  3,
  FALSE,
  NULL,
  'total',
  86,
  TRUE,
  NULL,
  ARRAY['isolation','hamstrings']::text[],
  ARRAY(SELECT id FROM muscle_groups WHERE slug IN ('glutes','calves') ORDER BY slug)::uuid[]
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug = 'machine-leg-curl');