-- Create comprehensive English and Romanian translations for all equipment items
INSERT INTO equipment_translations (equipment_id, language_code, name, description)
SELECT e.id, 'en', en_data.name, en_data.description
FROM equipment e
JOIN (
  VALUES
    ('ab-crunch-machine', 'Ab Crunch Machine', 'Machine for targeted abdominal crunches'),
    ('abductor-machine', 'Abductor Machine', 'Machine for hip abduction exercises'),
    ('adductor-machine', 'Adductor Machine', 'Machine for hip adduction exercises'),
    ('cable-machine', 'Cable Machine', 'Adjustable cable pulley system'),
    ('calf-raise-machine', 'Calf Raise Machine', 'Machine for calf muscle training'),
    ('chains', 'Chains', 'Heavy chains for variable resistance training'),
    ('chest-press-machine', 'Chest Press Machine', 'Machine for chest pressing movements'),
    ('decline-bench', 'Decline Bench', 'Declined bench for decline pressing'),
    ('dip-bars', 'Dip Bars', 'Parallel bars for dip exercises'),
    ('dumbbell', 'Dumbbell', 'Adjustable or fixed weight dumbbell'),
    ('elliptical', 'Elliptical', 'Elliptical trainer for cardio workouts'),
    ('ez-curl-bar', 'EZ Curl Bar', 'Angled barbell for bicep and tricep exercises'),
    ('fixed-barbell', 'Fixed Barbell', 'Pre-loaded fixed weight barbell'),
    ('flat-bench', 'Flat Bench', 'Horizontal bench for pressing exercises'),
    ('flywheel-trainer', 'Flywheel Trainer', 'Inertial flywheel training device'),
    ('glute-kickback-machine', 'Glute Kickback Machine', 'Machine for glute kickback exercises'),
    ('hack-squat-machine', 'Hack Squat Machine', 'Angled squat machine'),
    ('hip-thrust-machine', 'Hip Thrust Machine', 'Machine for hip thrust exercises'),
    ('hyperextension-bench', 'Hyperextension Bench', 'Bench for back hyperextension exercises'),
    ('incline-bench', 'Incline Bench', 'Angled bench for incline pressing'),
    ('kettlebell', 'Kettlebell', 'Cast iron weight with handle for dynamic exercises'),
    ('lat-pulldown-machine', 'Lat Pulldown Machine', 'Machine for lat pulldown exercises'),
    ('leg-curl-machine', 'Leg Curl Machine', 'Machine for hamstring curl exercises'),
    ('leg-extension-machine', 'Leg Extension Machine', 'Machine for quadriceps extension exercises'),
    ('leg-press-machine', 'Leg Press Machine', 'Machine for leg pressing exercises'),
    ('olympic-barbell', 'Olympic Barbell', 'Standard 45lb/20kg Olympic barbell'),
    ('parallel-bars', 'Parallel Bars', 'Parallel bars for gymnastics exercises'),
    ('pec-deck-machine', 'Pec Deck Machine', 'Machine for chest fly exercises'),
    ('power-cage', 'Power Cage', 'Multi-station power cage with safety bars'),
    ('pull-up-bar', 'Pull-up Bar', 'Overhead bar for pull-ups and chin-ups'),
    ('push-up-bars', 'Push-up Bars', 'Handles for elevated push-up exercises'),
    ('resistance-band', 'Resistance Band', 'Elastic band for resistance training'),
    ('roman-chair', 'Roman Chair', 'Bench for core and back exercises'),
    ('rower', 'Rower', 'Rowing machine for cardio and strength'),
    ('sandbag', 'Sandbag', 'Weighted sandbag for functional training'),
    ('seated-row-machine', 'Seated Row Machine', 'Cable machine for seated rowing'),
    ('shoulder-press-machine', 'Shoulder Press Machine', 'Machine for shoulder pressing exercises'),
    ('smith-machine', 'Smith Machine', 'Guided barbell machine with safety catches'),
    ('squat-rack', 'Squat Rack', 'Rack for squatting exercises'),
    ('stair-climber', 'Stair Climber', 'Machine simulating stair climbing'),
    ('stationary-bike', 'Stationary Bike', 'Exercise bike for cardio training'),
    ('torso-rotation-machine', 'Torso Rotation Machine', 'Machine for core rotation exercises'),
    ('trap-bar', 'Trap Bar', 'Hexagonal bar for deadlifts and shrugs'),
    ('treadmill', 'Treadmill', 'Running machine for cardio exercise'),
    ('weight-plate', 'Weight Plate', 'Additional weight plates for barbells')
) AS en_data(slug, name, description) ON e.slug = en_data.slug

UNION ALL

SELECT e.id, 'ro', ro_data.name, ro_data.description
FROM equipment e
JOIN (
  VALUES
    ('ab-crunch-machine', 'Mașina de Crunch Abdominal', 'Mașină pentru crunch-uri abdominale țintite'),
    ('abductor-machine', 'Mașina de Abducție', 'Mașină pentru exerciții de abducție șoldului'),
    ('adductor-machine', 'Mașina de Aducție', 'Mașină pentru exerciții de aducție șoldului'),
    ('cable-machine', 'Mașina cu Cablu', 'Sistem de scripete cu cablu reglabil'),
    ('calf-raise-machine', 'Mașina pentru Gambe', 'Mașină pentru antrenarea mușchilor gambei'),
    ('chains', 'Lanțuri', 'Lanțuri grele pentru antrenament cu rezistență variabilă'),
    ('chest-press-machine', 'Mașina de Presa Piept', 'Mașină pentru mișcări de presă la piept'),
    ('decline-bench', 'Bancă Declinată', 'Bancă declinată pentru presă în declin'),
    ('dip-bars', 'Bare pentru Dips', 'Bare paralele pentru exerciții de dips'),
    ('dumbbell', 'Ganteră', 'Ganteră cu greutate reglabilă sau fixă'),
    ('elliptical', 'Eliptică', 'Antrenor eliptic pentru antrenament cardio'),
    ('ez-curl-bar', 'Bară EZ', 'Bară unghiulară pentru exerciții biceps și triceps'),
    ('fixed-barbell', 'Bară Fixă', 'Bară cu greutate fixă pre-încărcată'),
    ('flat-bench', 'Bancă Plană', 'Bancă orizontală pentru exerciții de presă'),
    ('flywheel-trainer', 'Antrenor cu Volant', 'Dispozitiv de antrenament cu volant inerțial'),
    ('glute-kickback-machine', 'Mașina pentru Fesieri', 'Mașină pentru exerciții de kickback pentru fesieri'),
    ('hack-squat-machine', 'Mașina Hack Squat', 'Mașină de squat unghiulară'),
    ('hip-thrust-machine', 'Mașina Hip Thrust', 'Mașină pentru exerciții de hip thrust'),
    ('hyperextension-bench', 'Bancă de Hiperextensie', 'Bancă pentru exerciții de hiperextensie a spatelui'),
    ('incline-bench', 'Bancă Înclinată', 'Bancă unghiulară pentru presă în înclinare'),
    ('kettlebell', 'Kettlebell', 'Greutate din fontă cu mâner pentru exerciții dinamice'),
    ('lat-pulldown-machine', 'Mașina Lat Pulldown', 'Mașină pentru exerciții de lat pulldown'),
    ('leg-curl-machine', 'Mașina Leg Curl', 'Mașină pentru exerciții de curl la ischiogambieri'),
    ('leg-extension-machine', 'Mașina Leg Extension', 'Mașină pentru exerciții de extensie la quadriceps'),
    ('leg-press-machine', 'Mașina Leg Press', 'Mașină pentru exerciții de presă la picioare'),
    ('olympic-barbell', 'Bară Olimpică', 'Bară olimpică standard de 45lb/20kg'),
    ('parallel-bars', 'Bare Paralele', 'Bare paralele pentru exerciții de gimnastică'),
    ('pec-deck-machine', 'Mașina Pec Deck', 'Mașină pentru exerciții de fluture la piept'),
    ('power-cage', 'Cușcă de Forță', 'Cușcă de forță multi-stație cu bare de siguranță'),
    ('pull-up-bar', 'Bară de Tracțiuni', 'Bară suspendată pentru tracțiuni și chin-ups'),
    ('push-up-bars', 'Bare pentru Flotări', 'Mânere pentru exerciții de flotări ridicate'),
    ('resistance-band', 'Bandă de Rezistență', 'Bandă elastică pentru antrenament de rezistență'),
    ('roman-chair', 'Scaunul Roman', 'Bancă pentru exerciții de core și spate'),
    ('rower', 'Aparat de Vâslit', 'Mașină de vâslit pentru cardio și forță'),
    ('sandbag', 'Sac de Nisip', 'Sac cu nisip pentru antrenament funcțional'),
    ('seated-row-machine', 'Mașina Seated Row', 'Mașină cu cablu pentru vâslit așezat'),
    ('shoulder-press-machine', 'Mașina de Presă Umeri', 'Mașină pentru exerciții de presă la umeri'),
    ('smith-machine', 'Mașina Smith', 'Mașină cu bară ghidată cu sisteme de siguranță'),
    ('squat-rack', 'Rack pentru Squat', 'Rack pentru exerciții de squat'),
    ('stair-climber', 'Simulator de Scări', 'Mașină care simulează urcatul scărilor'),
    ('stationary-bike', 'Bicicletă Staționară', 'Bicicletă de exerciții pentru antrenament cardio'),
    ('torso-rotation-machine', 'Mașina de Rotație Trunchi', 'Mașină pentru exerciții de rotație a trunchiului'),
    ('trap-bar', 'Bară Trap', 'Bară hexagonală pentru deadlift-uri și ridicări de umeri'),
    ('treadmill', 'Banda de Alergare', 'Mașină de alergare pentru exerciții cardio'),
    ('weight-plate', 'Discuri de Greutate', 'Discuri de greutate suplimentare pentru bare')
) AS ro_data(slug, name, description) ON e.slug = ro_data.slug

ON CONFLICT (equipment_id, language_code) DO UPDATE SET
name = EXCLUDED.name,
description = EXCLUDED.description;